### PR TITLE
Add support for 6.1.52-valve16

### PR DESCRIPTION
**Pull request by lividhen**
Adds support for 6.1.52-valve16 allowing building on steamos 5.5.17

### CODE REVIEW

**Comment by badly-drawn-wizards** [comment]
Thank you.

**Comment by lzq960605** [comment]
> Adds support for 6.1.52-valve16 allowing building on steamos 5.5.17

Please adapt to the 6.1.52-valve19-1

**Comment by lividhen** [comment]
If you run the install script it should download the kernel your is is running and build the module. If it doesn't work or has any issues please let me know so I can fix it.

**Comment by lzq960605** [comment]
> If you run the install script it should download the kernel your is is running and build the module. If it doesn't work or has any issues please let me know so I can fix it.

/home/deck/Desktop/vangogh_oc_fix-master/install.sh: line 24: make: command not found
ln: failed to create symbolic link './build': File exists
/home/deck/Desktop/vangogh_oc_fix-master/install.sh: line 26: make: command not found
/home/deck/Desktop/vangogh_oc_fix-master/install.sh: line 27: make: command not found
Installing!
/home/deck/Desktop/vangogh_oc_fix-master/install.sh: line 30: make: command not found
[sudo] password for deck: 
Created symlink /etc/systemd/system/multi-user.target.wants/vangogh_oc_fix.service → /etc/systemd/system/vangogh_oc_fix.service.
Re-enabling read only.

**Comment by lividhen** [comment]
Do you have pacman set up? It looks like your missing the packages in the readme. Do `sudo pacman -S base-devel linux-neptune-61` and try again.  

Edit: sorry! Didn't see your issue or I would have responded there. You can either keep talking here or move the discussion to your issue. Whatever you feel like doing.

**Comment by lzq960605** [comment]
> Do you have pacman set up? It looks like your missing the packages in the readme. Do `sudo pacman -S base-devel linux-neptune-61` and try again.
> 
> Edit: sorry! Didn't see your issue or I would have responded there. You can either keep talking here or move the discussion to your issue. Whatever you feel like doing.

bro, I executed sudo pacman -S base-devel linux-neptune-61

==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly
(4/4) Managing kdump minimal initramfs
==> ERROR: binary not found: 'plymouth'
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
==> WARNING: Possibly missing '/bin/bash' for script: /usr/bin/mount.steamos
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly

**Comment by lividhen** [comment]
🤔 Not sure why it can't find Plymouth that's odd. Thanks for letting me know! I will look into it.

**Comment by lzq960605** [comment]
> 🤔 Not sure why it can't find Plymouth that's odd. Thanks for letting me know! I will look into it.

Bro, have you found any reason?

**Comment by lividhen** [comment]
Been busy with work but I plan to work on it tonight and / or tomorrow. Sorry for the wait!

**Comment by lividhen** [comment]
@lzq960605 If you install `linux-neptune-61-headers` what is the output?

**Pull request merged**
